#!/usr/bin/env node

'use strict';

require('../init');

var path = require('path');
var stream = require('../../dist/stream');
var Logger = require('../../dist/logger').default;
var Parser = require('../../dist/parser').default;

var parser = new Parser({logger: new Logger()});
var parseFilter = parser.stream();

parseFilter.promise.then(function (data) {
  console.log(JSON.stringify(data, undefined, 2));
});

stream.read(path.resolve(__dirname, 'test.scss')).pipe(parseFilter);
