'use strict';

module.exports = {

  parse: function (text) {
    return {
      description : text,
      autogenerated : false,
    };
  },

  default : function(item){
    if (item.context.code.indexOf('@content') > -1){
     return [{
       autogenerated : true
     }];
    }
  },

  allowedOn : ['mixin']
};
