'use strict';

var utils = require('../../utils');
module.exports = {

  parse: function (text) {
    return {
      description : text,
      autogenerated : false,
    };
  },

  resolve: function(byTypeAndName){
    utils.eachItem(byTypeAndName, function (item) {
      if (!utils.isset(item.content) &&
           utils.isset(item.context.code)){
        if (item.context.code.indexOf('@content') > -1){
          item.content = [{
            autogenerated : true
          }];
        }
      }
    });
  },

  allowedOn : ['mixin']
};
